# Generated by Django 2.2.16 on 2022-10-19 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10, message='Рейтинг не может быть больше 10.'), django.core.validators.MaxValueValidator(0, message='Рейтинг не может быть меньше 0.')], verbose_name='Рейтинг произведения'),
        ),
    ]
